name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade wheel
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint code
        run: |
          pylint src tests
      - name: Run tests
        run: |
          pytest